### ISSUE TITLE
Update MNIST tutorial to work with latest Fuel

### ISSUE THREAD

**Issue by haanvid** [bartvm/blocks#627] opened 2015-05-13 06:33 UTC
Hi I just installed the blocks and ran the example.
And while running the command below I had this dimension mismatch error 
>
_>>> main_loop.run() 
>

>

The error message:

>
_>>> main_loop.run()
INFO:blocks.main_loop:Entered the main loop
INFO:blocks.algorithms:Initializing the training algorithm
INFO:blocks.algorithms:The training algorithm is initialized
INFO:root:Monitoring on auxiliary data started
ERROR:blocks.main_loop:Error occured during training.
>
>
Blocks will attempt to run `on_error` extensions, potentially saving data, before exiting and reraising the error. Note that the usual `after_training` extensions will *not* be run. The original error will be re-raised and also stored in the training log. Press CTRL + C to halt Blocks immediately.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/blocks/main_loop.py", line 188, in run
    reraise_as(e)
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/blocks/utils/__init__.py", line 225, in reraise_as
    six.reraise(type(new_exc), new_exc, orig_exc_traceback)
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/blocks/main_loop.py", line 174, in run
    while self._run_epoch():
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/blocks/main_loop.py", line 221, in _run_epoch
    self._run_extensions('before_epoch')
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/blocks/main_loop.py", line 253, in _run_extensions
    extension.dispatch(CallbackName(method_name), *args)
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/blocks/extensions/__init__.py", line 330, in dispatch
    self.do(callback_invoked, *(from_main_loop + tuple(arguments)))
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/blocks/extensions/monitoring.py", line 79, in do
    value_dict = self._evaluator.evaluate(self.data_stream)
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/blocks/monitoring/evaluators.py", line 320, in evaluate
    self.process_batch(batch)
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/blocks/monitoring/evaluators.py", line 293, in process_batch
    numerical_values = self._accumulate_fun(**batch)
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 516, in __call__
    self[k] = arg
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 452, in __setitem__
    self.value[item] = value
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/theano/compile/function_module.py", line 415, in __setitem__
    s.value = value
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/theano/gof/link.py", line 278, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)
  File "/home/cuda1/anaconda/lib/python2.7/site-packages/theano/tensor/type.py", line 157, in filter
    data.shape))
TypeError: ('Wrong number of dimensions: expected 2, got 4 with shape (1024, 1, 28, 28)., Container name "features"\n\nOriginal exception:\n\tTypeError: Wrong number of dimensions: expected 2, got 4 with shape (1024, 1, 28, 28)., Container name "features"', 'Container name "features"')
>

Is it my system or the example?

Before this I also had problems with fuel and
solved it with the code suggested by @vdumoulin 
>
cd $FUEL_DATA_PATH
fuel-download mnist
fuel-convert mnist
fuel-download --clear mnist
cd -
>

**Comment by rizar** [comment] 2015-05-13 10:00
Wow, that's not nice! Thank you for reporting this, reproduced on my machine.

I am especially interested that Blocks automatic tests pass. 

@vdumoulin , I guess this bug is related to some recent Fuel changes.

**Comment by vdumoulin** [comment] 2015-05-13 11:10
This should have been fixed when the changes have been made in Fuel. When was your last pull of Fuel and Blocks?

**Comment by vdumoulin** [comment] 2015-05-13 11:19
I just updated both Fuel and Blocks to the latest commits and the example runs on my end.

**Comment by haanvid** [comment] 2015-05-13 11:34
@vdumoulin I just installed blocks using the commands that were on the Blocks site yesterday and ran it as it is. Thanks for the update, I will try on the updated one

**Comment by haanvid** [comment] 2015-05-13 13:26
To use the updated one, can I just download the blocks files in zip file and use the command $python setup.py install ?

**Comment by vdumoulin** [comment] 2015-05-13 13:41
Try typing `pip install --upgrade git+https://github.com/bartvm/fuel#egg=fuel`

**Comment by haanvid** [comment] 2015-05-14 01:19
@vdumoulin  Thanks!

**Comment by haanvid** [comment] 2015-05-14 12:49
@vdumoulin  I used the command you gave me right away but didn't work. So I formatted the computer and installed ubuntu, theano, and blocks again. and ran the example and it showed same error. So I used your command again for the second time and it showed same error message. And I had to still use 'fuel-convert mnist' command to use the mnist dataset... Will there be another solution for the problem?
>
_>>> main_loop.run()
INFO:blocks.main_loop:Entered the main loop
INFO:blocks.algorithms:Initializing the training algorithm
INFO:blocks.algorithms:The training algorithm is initialized
INFO:root:Monitoring on auxiliary data started
ERROR:blocks.main_loop:Error occured during training.
>
Blocks will attempt to run `on_error` extensions, potentially saving data, before exiting and reraising the error. Note that the usual `after_training` extensions will *not* be run. The original error will be re-raised and also stored in the training log. Press CTRL + C to halt Blocks immediately.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/main_loop.py", line 188, in run
    reraise_as(e)
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/utils/__init__.py", line 225, in reraise_as
    six.reraise(type(new_exc), new_exc, orig_exc_traceback)
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/main_loop.py", line 174, in run
    while self._run_epoch():
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/main_loop.py", line 221, in _run_epoch
    self._run_extensions('before_epoch')
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/main_loop.py", line 253, in _run_extensions
    extension.dispatch(CallbackName(method_name), *args)
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/extensions/__init__.py", line 330, in dispatch
    self.do(callback_invoked, *(from_main_loop + tuple(arguments)))
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/extensions/monitoring.py", line 79, in do
    value_dict = self._evaluator.evaluate(self.data_stream)
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/monitoring/evaluators.py", line 320, in evaluate
    self.process_batch(batch)
  File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/monitoring/evaluators.py", line 293, in process_batch
    numerical_values = self._accumulate_fun(**batch)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 532, in __call__
    self[k] = arg
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 468, in __setitem__
    self.value[item] = value
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 427, in __setitem__
    s.value = value
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 345, in __set__
    self.storage[0] = self.type.filter(value, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/type.py", line 169, in filter
    data.shape))
TypeError: ('Wrong number of dimensions: expected 2, got 4 with shape (1024, 1, 28, 28)., Container name "features"\n\nOriginal exception:\n\tTypeError: Wrong number of dimensions: expected 2, got 4 with shape (1024, 1, 28, 28)., Container name "features"', 'Container name "features"')
 

>

**Comment by vdumoulin** [comment] 2015-05-14 13:18
Which command are you talking about? Could you post the exact error message it returned?

**Comment by rizar** [comment] 2015-05-14 19:22
I confirm this is a version mismatch. To my embarrassment I spend some time figuring out why `~/dist/blocks/examples/mnist.py` does not work even though I reinstalled blocks and fuel. Of course, I had to either run examples from the installation directory or update `~/dist/blocks`. @haanvid , could it be that you are in a same situation?

But if you actually removed Ubuntu and installed everything from scratch, @haanvid, it is really strange that it does not work for you. Can you please show us the code of the actual file (`mnist.py`) you run?

And as @vdumoulin pointed out, this thread is more suitable for `blocks-users`. I will close the issue for it not to scare the newcomers (how's that, their simplest example doesn't work!), but we can continue figuring out what you do wrong here.

**Comment by haanvid** [comment] 2015-05-15 03:21
Running mnist.py in ~/block-master/examples by using the command:

>
~/blocks-master/examples$ python mnist.py 
>

 works fine except that I have to convert the datasets 
t10k-images-idx3-ubyte, t10k-labels-idx1-ubyte, train-images-idx3-ubyte, train-labels-idx1-ubyte into mnist.hdf5 file in the ubuntu terminal using the command that was given by @vdumoulin:
>
cd $FUEL_DATA_PATH
fuel-download mnist
fuel-convert mnist
fuel-download --clear mnist
cd -
>


Otherwise it will give error message:


>
~/blocks-master/examples$ python mnist.py 
Traceback (most recent call last):
  File "mnist.py", line 102, in <module>
    main(args.save_to, args.num_epochs, args.bokeh)
  File "mnist.py", line 44, in main
    mnist_train = MNIST("train")
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/mnist.py", line 36, in __init__
    super(MNIST, self).__init__(self.data_path, which_set, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 142, in __init__
    if which_set not in self.available_splits:
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 254, in available_splits
    return tuple(self.split_dict.keys())
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 235, in split_dict
    self._out_of_memory_open()
  File "/usr/local/lib/python2.7/dist-packages/fuel/datasets/hdf5.py", line 304, in _out_of_memory_open
    name=self.path, mode="r", driver=self.driver)
  File "/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_hl/files.py", line 260, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py-2.5.0-py2.7-linux-x86_64.egg/h5py/_hl/files.py", line 89, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/easy_install-zY3TVe/h5py-2.5.0/h5py/_objects.c:2453)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/easy_install-zY3TVe/h5py-2.5.0/h5py/_objects.c:2410)
  File "h5py/h5f.pyx", line 76, in h5py.h5f.open (/tmp/easy_install-zY3TVe/h5py-2.5.0/h5py/h5f.c:1787)
IOError: Unable to open file (Unable to open file: name = '/home/cuda1/datasets/mnist/mnist.hdf5', errno = 2, error message = 'no such file or d

>

The error mentioned that I earlier before this, was made while running the example code in the Blocks site copying and pasting the codes one by one. The site:
>
http://blocks.readthedocs.org/en/latest/tutorial.html
>

it gave the error that I wrote about it in the earlier comment:
(I ran it on the python command window)
>
_>>> main_loop.run()
>

The error message:
>
INFO:blocks.main_loop:Entered the main loop
INFO:blocks.algorithms:Initializing the training algorithm
INFO:blocks.algorithms:The training algorithm is initialized
INFO:root:Monitoring on auxiliary data started
ERROR:blocks.main_loop:Error occured during training.
>
Blocks will attempt to run on_error extensions, potentially saving data, before exiting and reraising the error. Note that the usual after_training extensions will not be run. The original error will be re-raised and also stored in the training log. Press CTRL + C to halt Blocks immediately.
Traceback (most recent call last):
File "", line 1, in
File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/main_loop.py", line 188, in run
reraise_as(e)
File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/utils/init.py", line 225, in reraise_as
six.reraise(type(new_exc), new_exc, orig_exc_traceback)
File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/main_loop.py", line 174, in run
while self.run_epoch():
File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/main_loop.py", line 221, in run_epoch
self._run_extensions('before_epoch')
File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/main_loop.py", line 253, in _run_extensions
extension.dispatch(CallbackName(method_name), *args)
File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/extensions/__init.py", line 330, in dispatch
self.do(callback_invoked, (from_main_loop + tuple(arguments)))
File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/extensions/monitoring.py", line 79, in do
value_dict = self._evaluator.evaluate(self.data_stream)
File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/monitoring/evaluators.py", line 320, in evaluate
self.process_batch(batch)
File "/usr/local/lib/python2.7/dist-packages/blocks-0.1a1-py2.7.egg/blocks/monitoring/evaluators.py", line 293, in process_batch
numerical_values = self._accumulate_fun(batch)
File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 532, in call
self[k] = arg
File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 468, in setitem
self.value[item] = value
File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 427, in setitem
s.value = value
File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 345, in set
self.storage[0] = self.type.filter(value, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/theano/tensor/type.py", line 169, in filter
data.shape))
TypeError: ('Wrong number of dimensions: expected 2, got 4 with shape (1024, 1, 28, 28)., Container name "features"\n\nOriginal exception:\n\tTypeError: Wrong number of dimensions: expected 2, got 4 with shape (1024, 1, 28, 28)., Container name "features"', 'Container name "features"')
>

For the installation of Theano and Blocks,
=====================================================================
I ran this two-lines of simple command to install Theano:
>
$ sudo apt-get install python-numpy python-scipy python-dev python-pip python-nose g++ libopenblas-dev git
$sudo pip install Theano
>

=====================================================================

For blocks, I used these commands to install it for the first time:
>
$ pip install cython
>

For the requirements mentioned in the site, I found them one by one and ran the commands:
>
http://blocks.readthedocs.org/en/latest/setup.html#requirements
>

pyyaml install

>
$ sudo apt-get install python-yaml
>

six install
>
$ pip install six
>

Toolz install
>
$ sudo pip install toolz
>

For optional(Bokeh):
>
$ sudo pip install pyzmq
$ pip install bokeh
>

>
http://blocks.readthedocs.org/en/latest/setup.html

$ pip install git+git://github.com/bartvm/blocks.git \
  -r https://raw.githubusercontent.com/bartvm/blocks/master/requirements.txt
>

And there was some errors about error code 1 so I installed what are in the site:
>
https://launchpad.net/ubuntu/+source/numexpr/2.2.2-4build1

https://github.com/PyTables/PyTables/tree/790f4e7c191f2f3f35fd5a3849bcb02d6f002c28
>

And running the codes in the tutorial in the site copying and pasting the codes one line at a time:
>
http://blocks.readthedocs.org/en/latest/tutorial.html
>

I found out that I had to convert the 4 dataset files into mnist.hdf5. manually by the commands suggested by @vdumoulin  while running the codes:
>
_>>> from fuel.datasets import MNIST
_>>> mnist = MNIST("train")
>

For datasets, I got it from the site mentioned in the tutorial:
>
http://blocks.readthedocs.org/en/latest/tutorial.html
http://yann.lecun.com/exdb/mnist/
>

Because after getting suggestions from @vdumoulin  about converting the files into mnist.hdf5, I tried downloading 'blocks-master.zip' from the github directly. And ran: 
>
$ sudo python setup.py install
>

To update(I don't have much experience with either ubuntu and python and github) the blocks
file.(wonder if it works that way) But same error messages were generated. And since @vdumoulin gave another suggestion of running the command:

>
$ pip install --upgrade git+https://github.com/bartvm/fuel#egg=fuel
>

I tired it. But same error message came out and did not work.

But as @rizar said, it works by running the command(was it mentioned on the tutorial?):

>
~/blocks-master/examples$ python mnist.py 
>

But still the dataset needs manual converting from [t10k-images-idx3-ubyte, t10k-labels-idx1-ubyte, train-images-idx3-ubyte, train-labels-idx1-ubyte] to mnist.hdf5.

And @rizar , sorry to bother you but can you teach me how to update certain part of the file?
>  
Of course, I had to either run examples from the installation directory or update ~/dist/blocks
>

I'm sorry to bother both of you but, I'm new to ubuntu and python and github. So I need specific details on running Blocks. If you see it from my point of view, it's frustrating because I found out Blocks was great and I thought Blocks would shorten my time on developing deep learning structures. So I wanted to use it. But while it took a minute to install Theano and to run it, Blocks already have cost me 3 whole days to just install and run the examples. I know that people in this field is good at this kind of stuff but please be noted that some are beginners

**Comment by rizar** [comment] 2015-05-15 08:39
@haanvid , yes you can write here.

It seems like you went wrong way from the very beginning, because as the [installation instruction](http://blocks.readthedocs.org/en/latest/setup.html) says, the right way to install Blocks is 

```
pip install git+git://github.com/bartvm/blocks.git \
  -r https://raw.githubusercontent.com/bartvm/blocks/master/requirements.txt
```

whereas your post suggests that you started installing dependencies one by one. Also, if you have a `blocks` version installed, you will have add `--upgrade` to the command in order to update it.

Next thing, what you were supposed to do, in order to run MNIST example or MNIST tutorial, is to download MNIST. We do not do it automatically for you because this is easy enough:

```
fuel-download mnist
fuel-convert mnist
```

That should be perhaps mentioned in the MNIST tutorial. 

Finally, unfortunately the [tutorial](http://blocks.readthedocs.org/en/latest/tutorial.html) was not updated after recent `Fuel` changes (@vdumoilin, can you please do it? Also, do you know why doctests pass?). The example `blocks/examples/mnist.py` was, so you can use it for the start.

Finally, I understand your frustration, but please also respect our efforts to create a good library, which requires constant refactoring, which in turn inevitably breaks things once in a while. We are just about to release 0.01 version, which will hopefully help with non-working tutorials and things like that.

**Comment by rizar** [comment] 2015-05-15 08:40
To be brief, that was our issue, namely:

```
>>> from fuel.streams import DataStream
>>> from fuel.schemes import SequentialScheme
>>> data_stream = DataStream(mnist, iteration_scheme=SequentialScheme( #???
...     mnist.num_examples, batch_size=256))
```

**Comment by haanvid** [comment] 2015-05-15 09:09
I see, so I didn't read that the requirements were already in:

>
pip install git+git://github.com/bartvm/blocks.git \
  -r https://raw.githubusercontent.com/bartvm/blocks/master/requirements.txt
>

Sorry for the trouble and thanks!

**Comment by vdumoulin** [comment] 2015-05-15 11:15
My bad, I didn't see that this tutorial needed updating.

The reason why the tests pass is because in `.travis.yml` MNIST is downloaded and cached before these tests are run.

Yesterday I added a section in the online Fuel documentation that explains how to get started with built-in datasets. We can link to that in the MNIST tutorial.

The only problem is ReadTheDocs didn't update the online docs. @bartvm could you nudge it a little?

**Comment by bartvm** [comment] 2015-05-15 13:22
*sigh* There's some sort of HDF5 library issue... I'll try and fix it, but it might need more than a nudge.

**Closed** 2015-05-15 13:28 UTC
Labels: bug, major

**Comment by vdumoulin** [comment] 2015-05-15 13:49
Alright. In that case, it might be a good idea to temporarily point to the `.rst` file on Github while this is being resolved

**Comment by rizar** [comment] 2015-05-15 13:58
Nice idea!

**Comment by Creative-Punch** [comment] 2015-06-10 13:13
Hi,

I am currently getting the same error when I run the code from https://github.com/udibr/VAE (after fixing the import errors due to renames of Dump and LoadFromDump)

I am using the latest blocks and fuel

**Comment by bartvm** [comment] 2015-06-10 13:19
Are you using the `Flatten` transformer as shown in the tutorial?

```python
>>> data_stream = Flatten(DataStream.default_stream(
...     mnist,
...     iteration_scheme=SequentialScheme(mnist.num_examples, batch_size=256)))
```

**Comment by haanvid** [comment] 2015-06-10 20:00
Sorry but I'm currently working with Theano so I don't know much about it

2015년 6월 10일 수요일, Bart van Merriënboer<notifications@github.com>님이 작성한 메시지:
