### ISSUE TITLE
The Theano toposort we use is n^2

### ISSUE THREAD

**Issue by rizar** [bartvm/blocks#177] opened 2015-01-30 10:25 UTC
Which makes it run 1 minute on my gradient computation graph.

I found lots of toposort's in Theano and can not figure out what is the simplest way to get my apply nodes sorted in linear time. @nouiz, @lamblin, can you give me a hint?

**Comment by nouiz** [comment] 2015-01-30 13:57
toposort isn't always the same implementation. It depend when this happend.
At the start of Theano optimization, when there is no op with destroy_map,
we use a faster version that do not check for  cycle in the graph. That is
faster. But as soon as we have op with destroy_map, there can be cycle in
the graph and you must add this extra check that is costly.

From what you told, the toposort is done in the grad. So it should use the
"fast" version. Where do you find the n^2 number? I never computed it. But
I never saw a problem with the "fast" version.

Can you show the toposort that cause problem? When I want to make Theano
optimization faster, most of the time if there is problem of slowness due
to toposort, I try to call it less often. And up to now, this always worked.

**Comment by rizar** [comment] 2015-01-30 14:07
I am sorry, I did not make myself clear.

In Blocks we offer the user some additional tools to work with Theano graphs. In order to do so, the first thing we do with the Theano graph is extracting all the variables in the topological order. Here is a link to the code that does it: https://github.com/bartvm/blocks/blob/master/blocks/graph.py#L86

The problem is that the `sort_apply_nodes` routine we use is quadratic (due to https://github.com/Theano/Theano/blob/master/theano/gof/sched.py#L163). So my question is: which toposort function from Theano should we use. There are a quite a few of them with very little documentation, and it is not clear which one will not be, for instance, removed in the next release.

I am not sure I understand how can we have cycles in Theano graphs.

**Comment by nouiz** [comment] 2015-01-30 14:18
I use theano.gof.graph.io_toposort(inputs, outputs) when I need a
deterministic order but, do not care if that order is a valid execution
order. To my knowledge it is the fastest implementation in Theano.

I do not think we will remove some of the implementation. Try it. If it is
too slow, tell me.

**Comment by rizar** [comment] 2015-01-30 14:46
I've tried and it seems to work correctly and fast. But I am not sure I understand what you mean by "deterministic but not valid execution order". Doesn't it ensure that if a node A has an output of a node B as its input, then B will appear earlier in the returned list? From the code it seems it does, and why isn't it a valid execution order?

**Comment by nouiz** [comment] 2015-01-30 15:05
The case you describe is done by this method. The problem is related to
destroy_map. Do you know what it is?

Quickly, if a Theano op have an output that is a view of an input like
v[i], Theano need to know that. Another case is if for speed/memory
optimization, during Theano optimization Theano create an op that return
one of its input, but also changed this value. This is the equivalent of
"b+=3" in numpy. The user can also explicitly add such op in his graph. But
this is highly discouraged. Theano can do a better and saver work on this.
So it do not happen frequenly, but I tell it just to express, that it is
not just Theano optimizer that do it.

destroy_map is the way an op tell Theano that a given output is the same
object as the corresponding input, but with changed value. view_map is the
mechanism that allow an op to tell Theano this output is a view of that
input.
(more doc on this:
http://deeplearning.net/software/theano/extending/inplace.html#views-and-inplace
)


When we have ops with destroy_map, this add constrain in the order of
execution. io_toposort do not take care of those constrain from memory.

For the possibility of cycle in the graph, this can only happen with
destroy_map. If the graph do no have such operation, then we can't have a
cycle. I also forgot the case when this can happen. Maybe I should take the
time to find an example of such graph and document it. Here is a case:
https://github.com/Theano/Theano/blob/a72f34bc01e6061eb6bce72f7c6cd35682e3540d/theano/gof/tests/test_destroyhandler.py#L204
I made a ticket to document it:

https://github.com/Theano/Theano/issues/2453

Do you need a valid execution order? Was I clear enough on why the
execution order depend of the destroy_map?

**Comment by rizar** [comment] 2015-01-30 15:10
OK, I think I understand now. No, we do not care about the level of view_map and destroy_map, we need topological order in the basic, user level sense.  @bartvm , correct me if I am wrong.

Thank you very much for quick help!

**Comment by bartvm** [comment] 2015-02-01 15:04
Fixed in #184 I believe.

**Closed by bartvm** 2015-02-01 15:04 UTC
Labels: bug, major
